language: php
php:
  - 8.1
script: ./vendor/bin/pest --teamcity --coverage --configuration ./phpunit.xml
after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
